# Docker compose file to support dev+ops activities
version: "3.3"

services:
  # Feedback API (from in this repository)
  http-server1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: appuser
        group: appgroup
        uid: "${_UID:-1000}"
        gid: "${_GID:-1000}"
    stdin_open: false
    tty: false
    hostname: http-server1.local
    container_name: http-server1.local
    ports:
      - ${HTTP_PORT:-8001}:${HTTP_PORT:-8001}
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp-server1.local}
      - SMTP_PORT=${SMTP_PORT:-1025}
      - SMTP_USERNAME=${SMTP_USERNAME:-xxx}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-xxx}
      - SMTP_USE_TLS=${SMTP_USE_TLS:-false}
      - HTTP_PORT=${HTTP_PORT:-8001}
    depends_on:
      - smtp-server1
    deploy: # with --compatibility when needed
      resources:
        limits:
          cpus: '1'
          memory: 256M

  # Simple SMTP server for dev and CI purpose
  smtp-server1:
    build:
      context: docker/smtp-server
      dockerfile: Dockerfile
    stdin_open: false
    tty: false
    hostname: smtp-server1.local
    container_name: smtp-server1.local
    command: python3 -m aiosmtpd --nosetuid --listen ${SMTP_SERVER:-smtp-server1.local}:${SMTP_PORT:-1025}
    # The following works too, but is deprectated (https://peps.python.org/pep-0594/#smtpd)
    # command: python3 -m smtpd --class DebuggingServer --nosetuid ${SMTP_SERVER:-smtp-server1.local}:${SMTP_PORT:-1025}
    ports:
      - ${SMTP_PORT:-1025}:${SMTP_PORT:-1025}
    environment:
      - PYTHONUNBUFFERED=1
      - TO_MAILBOX=${TO_MAILBOX:-no-reply@localhost}
    deploy: # with --compatibility when needed
      resources:
        limits:
          cpus: '1'
          memory: 256M
