---
name: Docker Hub

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      id: checkout
      uses: actions/checkout@v3

    - name: Determine target tag
      id: target
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "github.ref_type: ${{ github.ref_type }}"
        if [ ${{ github.ref_type }} == 'branch' ]; then
          echo "target_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
          echo "target_tag=$(git describe --tags --always)" >> $GITHUB_ENV
        fi
        cat $GITHUB_ENV

    - name: Build the Docker image
      id: build
      run: |
        docker build . --file Dockerfile --tag feedback-api:${{ env.target_tag }} --build-arg VERSION_TAG=${{ env.target_tag }}

    - name: List images
      id: list
      run: docker images

    - name: Login to Docker Hub
      id: login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      #if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'

    - name: Push to docker hub
      id: push-tag
      run: docker push feedback-api:${{ env.target_tag }}
      if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'

    - name: Push to docker hub latest
      id: push-latest
      run: |
        docker tag feedback-api:${{ env.target_tag }} feedback-api:latest
        docker push feedback-api:latest
      if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
